
import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from "@google/genai";
import { 
  Gamepad2, 
  Upload, 
  FileText, 
  Play, 
  CheckCircle, 
  XCircle, 
  Trophy, 
  RotateCcw, 
  ArrowRight,
  AlertCircle,
  BrainCircuit,
  Sparkles,
  Timer,
  Linkedin,
  Facebook,
  Twitter,
  Copy,
  Zap,
  AlignLeft,
  Share2
} from 'lucide-react';

const SYSTEM_INSTRUCTION = `You are an educational AI engine that generates interactive quiz games for students.

Your role is to create a live quiz session strictly based on the provided input content.

IMPORTANT RULES:
1. Use ONLY the given source content.
2. Generate EXACTLY 10 multiple-choice questions (MCQs).
3. Each question must have 4 options (A, B, C, D).
4. Only ONE option must be correct.
5. Questions should test understanding, not memorization.
6. Do not include any external knowledge.

QUIZ GAME BEHAVIOR CONTEXT:
- The quiz will be presented one question at a time.
- The student selects one option per question.
- The system will immediately check correctness.
- Correct answers will turn GREEN.
- Wrong answers will turn RED.
- Score is calculated by the system.
- Explanations are shown ONLY after quiz completion.

YOUR TASK:
1. Analyze the input content carefully.
2. Identify the most important concepts.
3. Generate 10 MCQs covering the content evenly.
4. Ensure options are not ambiguous.
5. Provide correct answers and clear explanations for review mode.

OUTPUT FORMAT:
Return STRICT JSON ONLY. No markdown. No commentary.

{
  "quiz_title": "<auto-generated based on content>",
  "total_questions": 10,
  "questions": [
    {
      "question_no": 1,
      "question_text": "",
      "options": {
        "A": "",
        "B": "",
        "C": "",
        "D": ""
      },
      "correct_option": "A",
      "correct_answer": "",
      "explanation": ""
    }
  ]
}`;

interface Question {
  question_no: number;
  question_text: string;
  options: { [key: string]: string };
  correct_option: string;
  correct_answer: string;
  explanation: string;
}

interface QuizData {
  quiz_title: string;
  total_questions: number;
  questions: Question[];
}

// --- Badge Definitions ---
type BadgeType = 'rookie' | 'apprentice' | 'elite' | 'lightning';

interface BadgeConfig {
  id: BadgeType;
  title: string;
  description: string;
  gradient: string;
  icon: React.ElementType;
  textColor: string;
  borderColor: string;
}

const BADGES: Record<BadgeType, BadgeConfig> = {
  rookie: {
    id: 'rookie',
    title: 'Rookie Scout',
    description: 'A good start! Keep practicing to unlock your potential.',
    gradient: 'from-orange-100 to-orange-200',
    borderColor: 'border-orange-300',
    textColor: 'text-orange-900',
    icon: FileText
  },
  apprentice: {
    id: 'apprentice',
    title: 'Rising Star',
    description: 'Solid effort! You are on your way to mastery.',
    gradient: 'from-blue-100 to-indigo-200',
    borderColor: 'border-indigo-300',
    textColor: 'text-indigo-900',
    icon: BrainCircuit
  },
  elite: {
    id: 'elite',
    title: 'Elite Scholar',
    description: 'Outstanding performance! You have a deep understanding.',
    gradient: 'from-yellow-100 to-amber-200',
    borderColor: 'border-amber-300',
    textColor: 'text-amber-900',
    icon: Trophy
  },
  lightning: {
    id: 'lightning',
    title: 'Lightning Grandmaster',
    description: 'Perfect Score & Blazing Speed! Truly legendary status.',
    gradient: 'from-purple-500 via-pink-500 to-red-500',
    borderColor: 'border-purple-400',
    textColor: 'text-white',
    icon: Zap
  }
};

const QuizLoader = () => {
  const [progress, setProgress] = useState(0);
  const [stepIndex, setStepIndex] = useState(0);
  
  const steps = [
    "Analyzing your content...",
    "Extracting key concepts...",
    "Drafting challenging questions...",
    "Verifying answers...",
    "Finalizing your quiz..."
  ];

  useEffect(() => {
    const timer = setInterval(() => {
      setProgress(old => {
        if (old >= 95) return old;
        return Math.min(old + Math.random() * 3, 95);
      });
    }, 150);

    const stepTimer = setInterval(() => {
       setStepIndex(prev => (prev < steps.length - 1 ? prev + 1 : prev));
    }, 1200);

    return () => {
      clearInterval(timer);
      clearInterval(stepTimer);
    };
  }, []);

  return (
    <div className="h-full min-h-[600px] flex flex-col items-center justify-center p-8 bg-page relative overflow-hidden">
       {/* Background Effects */}
       <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/3 left-1/2 -translate-x-1/2 w-96 h-96 bg-brand/5 rounded-full blur-3xl animate-pulse"></div>
       </div>

       <div className="relative z-10 flex flex-col items-center text-center max-w-md w-full">
          <div className="relative w-24 h-24 mb-8">
             <div className="absolute inset-0 border-4 border-brand/20 rounded-full"></div>
             <div className="absolute inset-0 border-4 border-brand rounded-full border-t-transparent animate-spin"></div>
             <div className="absolute inset-0 flex items-center justify-center">
                <BrainCircuit className="w-10 h-10 text-brand" />
             </div>
             <div className="absolute -top-2 -right-2 bg-card rounded-full p-1 shadow-sm animate-bounce border border-border">
                <Sparkles className="w-4 h-4 text-yellow-500" />
             </div>
          </div>

          <h3 className="text-2xl font-bold text-txt mb-2 transition-all duration-300 min-h-[2rem]">
            {steps[stepIndex]}
          </h3>
          
          <div className="w-64 bg-muted/20 rounded-full h-1.5 mt-6 overflow-hidden">
             <div 
               className="bg-brand h-full rounded-full transition-all duration-100 ease-out"
               style={{ width: `${progress}%` }}
             ></div>
          </div>
          
          <p className="text-muted text-xs mt-3 font-medium tracking-wider uppercase">
             AI Processing • {Math.round(progress)}%
          </p>
       </div>
    </div>
  );
};

const QuizGame = () => {
  // --- Setup State ---
  const [activeTab, setActiveTab] = useState<'text' | 'file'>('text');
  const [sourceText, setSourceText] = useState("");
  const [sourceFile, setSourceFile] = useState<File | null>(null);
  const [gameState, setGameState] = useState<'setup' | 'loading' | 'playing' | 'finished'>('setup');
  const [error, setError] = useState<string | null>(null);

  // --- Game State ---
  const [quizData, setQuizData] = useState<QuizData | null>(null);
  const [currentQIndex, setCurrentQIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [isAnswerRevealed, setIsAnswerRevealed] = useState(false);
  
  // --- Time & Badge State ---
  const [startTime, setStartTime] = useState<number>(0);
  const [endTime, setEndTime] = useState<number>(0);
  const [timeTaken, setTimeTaken] = useState<string>("");

  // --- Helpers ---
  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve((reader.result as string).split(',')[1]);
      reader.onerror = error => reject(error);
    });
  };

  const handleStartGame = async () => {
    if ((activeTab === 'text' && !sourceText.trim()) || (activeTab === 'file' && !sourceFile)) {
      setError("Please provide source content to generate the quiz.");
      return;
    }

    setGameState('loading');
    setError(null);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const parts: any[] = [];

      if (activeTab === 'file' && sourceFile) {
        const base64 = await fileToBase64(sourceFile);
        parts.push({
          inlineData: {
            mimeType: sourceFile.type,
            data: base64
          }
        });
      }
      
      const userPrompt = `SOURCE CONTENT:\n${activeTab === 'text' ? sourceText : '(See attached file)'}`;
      parts.push({ text: userPrompt });

      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: { parts },
        config: {
          systemInstruction: SYSTEM_INSTRUCTION,
          responseMimeType: 'application/json',
          temperature: 0.4
        }
      });

      const text = response.text;
      if (!text) throw new Error("Failed to generate quiz data.");

      const data: QuizData = JSON.parse(text);
      setQuizData(data);
      setGameState('playing');
      setCurrentQIndex(0);
      setScore(0);
      setSelectedOption(null);
      setIsAnswerRevealed(false);
      setStartTime(Date.now()); // Start Timer

    } catch (err: any) {
      console.error(err);
      setError(err.message || "An error occurred while generating the quiz.");
      setGameState('setup');
    }
  };

  const handleOptionClick = (optionKey: string) => {
    if (isAnswerRevealed) return;
    
    setSelectedOption(optionKey);
    setIsAnswerRevealed(true);

    const currentQ = quizData?.questions[currentQIndex];
    if (currentQ && optionKey === currentQ.correct_option) {
      setScore(prev => prev + 1);
    }
  };

  const handleNextQuestion = () => {
    if (!quizData) return;
    
    if (currentQIndex < quizData.questions.length - 1) {
      setCurrentQIndex(prev => prev + 1);
      setSelectedOption(null);
      setIsAnswerRevealed(false);
    } else {
      const end = Date.now();
      setEndTime(end);
      
      // Calculate duration
      const durationSec = Math.floor((end - startTime) / 1000);
      const min = Math.floor(durationSec / 60);
      const sec = durationSec % 60;
      setTimeTaken(`${min}m ${sec}s`);

      setGameState('finished');
    }
  };

  const handleRestart = () => {
    setGameState('setup');
    setQuizData(null);
    setSourceText("");
    setSourceFile(null);
    setScore(0);
  };

  // --- Badge Determination Logic ---
  const getBadge = (): BadgeConfig => {
    if (!quizData) return BADGES.rookie;
    
    const total = quizData.questions.length;
    const durationSec = Math.floor((endTime - startTime) / 1000);
    
    // 4. Lightning Master: Perfect Score + Fast Time (< 2 mins)
    if (score === total && durationSec < 120) {
      return BADGES.lightning;
    }
    // 3. Elite: > 6
    if (score > 6) {
      return BADGES.elite;
    }
    // 2. Apprentice: > 3
    if (score > 3) {
      return BADGES.apprentice;
    }
    // 1. Rookie: 3 or less
    return BADGES.rookie;
  };
  
  const handleShare = async (platform: 'native' | 'linkedin' | 'twitter' | 'facebook' | 'copy', badge: BadgeConfig) => {
    const text = `I just earned the "${badge.title}" badge on QBank Pro Live Quiz! 🏆\nScore: ${score}/10\nTime: ${timeTaken}\n\nCan you beat my score? #QBankPro #Learning #AI`;
    const url = window.location.href;

    if (platform === 'native') {
       if (navigator.share) {
          try {
             await navigator.share({
                title: 'QBank Pro Achievement',
                text: text,
                url: url
             });
          } catch (err) {
             console.error('Share failed:', err);
          }
       } else {
          handleShare('copy', badge);
       }
       return;
    }

    switch(platform) {
        case 'linkedin':
            window.open(`https://www.linkedin.com/feed/?shareActive=true&text=${encodeURIComponent(text)}`, '_blank');
            break;
        case 'twitter':
            window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`, '_blank');
            break;
        case 'facebook':
            window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(text)}`, '_blank');
            break;
        case 'copy':
            navigator.clipboard.writeText(text);
            alert("Share text copied to clipboard!");
            break;
    }
  };

  // --- RENDERERS ---

  if (gameState === 'loading') {
    return <QuizLoader />;
  }

  if (gameState === 'finished' && quizData) {
    const badge = getBadge();
    const BadgeIcon = badge.icon;

    return (
      <div className="max-w-4xl mx-auto p-6 space-y-8 animate-in zoom-in-95 duration-500 font-sans">
         
         {/* Badge & Score Card */}
         <div className={`relative overflow-hidden rounded-3xl bg-gradient-to-br ${badge.gradient} border-2 ${badge.borderColor} shadow-xl text-center p-10`}>
             <div className="relative z-10 flex flex-col items-center">
                 <div className={`w-32 h-32 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center mb-6 shadow-lg border-4 ${badge.borderColor} animate-bounce`}>
                    <BadgeIcon className={`w-16 h-16 ${badge.textColor}`} />
                 </div>
                 
                 <h1 className={`text-4xl md:text-5xl font-extrabold ${badge.textColor} mb-2 tracking-tight`}>{badge.title}</h1>
                 <p className={`text-lg ${badge.textColor} opacity-90 max-w-lg mx-auto font-medium`}>{badge.description}</p>
                 
                 <div className="grid grid-cols-2 gap-8 mt-8 w-full max-w-sm">
                    <div className="bg-white/20 backdrop-blur-md rounded-2xl p-4 border border-white/30 shadow-inner">
                       <p className={`text-xs uppercase tracking-widest font-bold ${badge.textColor} opacity-80`}>Score</p>
                       <p className={`text-3xl font-black ${badge.textColor}`}>{score}/10</p>
                    </div>
                    <div className="bg-white/20 backdrop-blur-md rounded-2xl p-4 border border-white/30 shadow-inner">
                       <p className={`text-xs uppercase tracking-widest font-bold ${badge.textColor} opacity-80`}>Time</p>
                       <p className={`text-3xl font-black ${badge.textColor}`}>{timeTaken}</p>
                    </div>
                 </div>

                 {/* Social Sharing */}
                 <div className="mt-8 flex flex-col items-center gap-4 w-full animate-in slide-in-from-bottom-4 delay-200">
                    <p className={`text-xs font-bold uppercase tracking-wide ${badge.textColor} opacity-80`}>Share Your Achievement</p>
                    
                    <div className="flex flex-wrap justify-center gap-3">
                         {/* Native Share / Primary Share */}
                        <button 
                          onClick={() => handleShare('native', badge)}
                          className="px-6 py-2.5 bg-white/30 backdrop-blur-md border border-white/50 rounded-full text-white font-bold shadow-lg hover:scale-105 transition-all flex items-center gap-2 hover:bg-white/40"
                        >
                            <Share2 className="w-5 h-5" /> Share Result
                        </button>
                    </div>

                    <div className="flex gap-2 opacity-80 hover:opacity-100 transition-opacity">
                        <button onClick={() => handleShare('linkedin', badge)} className="p-2 bg-white/90 text-[#0077b5] rounded-full hover:scale-110 transition-transform shadow-sm" title="Share on LinkedIn"><Linkedin className="w-5 h-5" /></button>
                        <button onClick={() => handleShare('twitter', badge)} className="p-2 bg-white/90 text-[#1DA1F2] rounded-full hover:scale-110 transition-transform shadow-sm" title="Share on Twitter"><Twitter className="w-5 h-5" /></button>
                        <button onClick={() => handleShare('facebook', badge)} className="p-2 bg-white/90 text-[#4267B2] rounded-full hover:scale-110 transition-transform shadow-sm" title="Share on Facebook"><Facebook className="w-5 h-5" /></button>
                        <button onClick={() => handleShare('copy', badge)} className="p-2 bg-white/90 text-gray-700 rounded-full hover:scale-110 transition-transform shadow-sm" title="Copy Text"><Copy className="w-5 h-5" /></button>
                    </div>
                 </div>
             </div>
             
             {/* Background Decoration */}
             <div className="absolute top-0 left-0 w-full h-full opacity-10 pointer-events-none">
                 <div className="absolute top-10 left-10 w-32 h-32 bg-white rounded-full blur-3xl"></div>
                 <div className="absolute bottom-10 right-10 w-40 h-40 bg-white rounded-full blur-3xl"></div>
             </div>
         </div>

         {/* Actions */}
         <div className="flex justify-center">
             <button 
               onClick={handleRestart}
               className="px-8 py-3 bg-card border border-border text-txt rounded-full font-bold shadow-sm hover:bg-muted/10 hover:scale-105 transition-all flex items-center gap-2"
             >
                <RotateCcw className="w-5 h-5" /> Play Again
             </button>
         </div>

         {/* Review Section */}
         <div className="space-y-6 pt-8 border-t border-border">
            <h3 className="text-xl font-bold text-txt px-2">Review Answers</h3>
            {quizData.questions.map((q, idx) => (
               <div key={idx} className="bg-card border border-border rounded-xl p-6 shadow-sm">
                  <div className="flex gap-4">
                     <div className="w-8 h-8 rounded-full bg-brand/10 text-brand flex items-center justify-center font-bold flex-shrink-0 text-sm border border-brand/20">
                        {idx + 1}
                     </div>
                     <div className="space-y-3 flex-1">
                        <h4 className="font-medium text-txt text-lg leading-snug">{q.question_text}</h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                           {Object.entries(q.options).map(([key, text]) => (
                              <div key={key} className={`
                                 p-3 rounded-lg border text-sm flex items-center gap-3 transition-colors
                                 ${key === q.correct_option 
                                    ? 'bg-green-500/10 border-green-500/30 text-green-700 dark:text-green-400' 
                                    : 'bg-page border-border text-muted'}
                              `}>
                                 <span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold border ${key === q.correct_option ? 'border-green-600 bg-green-600 text-white' : 'border-border text-muted'}`}>
                                    {key}
                                 </span>
                                 {text}
                              </div>
                           ))}
                        </div>
                        <div className="mt-3 p-4 bg-brand/5 rounded-lg text-sm text-txt border border-brand/10">
                           <span className="font-bold block mb-1 text-brand">Explanation:</span>
                           {q.explanation}
                        </div>
                     </div>
                  </div>
               </div>
            ))}
         </div>
      </div>
    );
  }

  if (gameState === 'playing' && quizData) {
    const currentQ = quizData.questions[currentQIndex];
    const progress = ((currentQIndex + 1) / quizData.questions.length) * 100;

    return (
       <div className="max-w-3xl mx-auto p-6 h-full flex flex-col justify-center min-h-[600px]">
          {/* Header */}
          <div className="mb-8">
             <div className="flex justify-between items-end mb-2">
                <span className="text-sm font-bold text-brand tracking-wider uppercase">Question {currentQIndex + 1} / {quizData.questions.length}</span>
                <div className="flex items-center gap-4">
                    <span className="text-xs font-medium text-muted flex items-center gap-1"><Timer className="w-4 h-4"/> Timing...</span>
                    <span className="text-sm font-bold text-txt">Score: {score}</span>
                </div>
             </div>
             <div className="w-full bg-muted/20 rounded-full h-2 overflow-hidden">
                <div className="bg-brand h-full transition-all duration-500 ease-out" style={{ width: `${progress}%` }}></div>
             </div>
          </div>

          {/* Question Card */}
          <div className="bg-card border border-border rounded-2xl p-8 shadow-glass animate-in slide-in-from-right-8 duration-300">
              <h2 className="text-2xl font-bold text-txt mb-8 leading-snug">{currentQ.question_text}</h2>

              <div className="space-y-3">
                 {Object.entries(currentQ.options).map(([key, text]) => {
                    let btnClass = "bg-page border-border hover:border-brand/50 hover:bg-brand/5 text-txt"; // Default
                    let indicatorClass = "border-border text-muted";

                    if (isAnswerRevealed) {
                       if (key === currentQ.correct_option) {
                          btnClass = "bg-green-500/10 border-green-500 text-green-700 dark:text-green-400"; // Correct
                          indicatorClass = "border-green-600 bg-green-600 text-white";
                       } else if (key === selectedOption) {
                          btnClass = "bg-red-500/10 border-red-500 text-red-700 dark:text-red-400 opacity-60"; // Wrong selected
                          indicatorClass = "border-red-600 bg-red-600 text-white";
                       } else {
                          btnClass = "bg-page border-transparent opacity-50"; // Others
                       }
                    }

                    return (
                       <button
                         key={key}
                         disabled={isAnswerRevealed}
                         onClick={() => handleOptionClick(key)}
                         className={`w-full p-4 rounded-xl border-2 text-left transition-all duration-200 flex items-center gap-4 ${btnClass}`}
                       >
                          <div className={`w-8 h-8 rounded-full border-2 flex items-center justify-center font-bold text-sm flex-shrink-0 ${indicatorClass}`}>
                             {key}
                          </div>
                          <span className="font-medium">{text}</span>
                          {isAnswerRevealed && key === currentQ.correct_option && <CheckCircle className="w-5 h-5 text-green-600 ml-auto" />}
                          {isAnswerRevealed && key === selectedOption && key !== currentQ.correct_option && <XCircle className="w-5 h-5 text-red-600 ml-auto" />}
                       </button>
                    );
                 })}
              </div>
          </div>

          {/* Footer Actions */}
          <div className="mt-8 h-16 flex justify-end">
             {isAnswerRevealed && (
                <button 
                  onClick={handleNextQuestion}
                  className="px-8 py-3 bg-brand text-inv rounded-xl font-bold shadow-lg shadow-brand/20 hover:bg-brand-hover transition-all flex items-center gap-2 animate-in fade-in slide-in-from-bottom-2"
                >
                   {currentQIndex < quizData.questions.length - 1 ? 'Next Question' : 'Finish Quiz'} <ArrowRight className="w-5 h-5" />
                </button>
             )}
          </div>
       </div>
    );
  }

  // --- SETUP VIEW ---
  return (
    <div className="min-h-screen bg-page p-6 flex flex-col items-center">
      <div className="w-full max-w-2xl space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
         
         <div className="text-center space-y-4">
            <div className="w-16 h-16 bg-brand/10 text-brand rounded-2xl flex items-center justify-center mx-auto shadow-sm transform rotate-3 border border-brand/20">
               <Gamepad2 className="w-8 h-8" />
            </div>
            <h1 className="text-3xl font-extrabold text-txt tracking-tight">Live Quiz Game</h1>
            <p className="text-muted text-lg max-w-md mx-auto">Turn your notes into an interactive 10-question challenge instantly.</p>
         </div>

         <div className="bg-card border border-border rounded-2xl shadow-sm overflow-hidden">
             <div className="flex border-b border-border bg-page/50 px-5 py-3 items-center gap-2">
                 <AlignLeft className="w-4 h-4 text-muted" />
                 <h2 className="font-semibold text-txt text-sm uppercase tracking-wide">Input Source</h2>
             </div>
             
             <div className="p-1 bg-page flex border-b border-border">
                <button 
                  onClick={() => setActiveTab('text')}
                  className={`flex-1 py-2 text-sm font-medium flex items-center justify-center gap-2 rounded-t-lg transition-colors ${activeTab === 'text' ? 'bg-card text-brand border-t-2 border-brand' : 'text-muted hover:text-txt'}`}
                >
                  <FileText className="w-4 h-4" /> Paste Text
                </button>
                <button 
                  onClick={() => setActiveTab('file')}
                  className={`flex-1 py-2 text-sm font-medium flex items-center justify-center gap-2 rounded-t-lg transition-colors ${activeTab === 'file' ? 'bg-card text-brand border-t-2 border-brand' : 'text-muted hover:text-txt'}`}
                >
                  <Upload className="w-4 h-4" /> Upload File
                </button>
             </div>
             
             <div className="p-6">
                {activeTab === 'text' ? (
                   <textarea 
                     value={sourceText}
                     onChange={(e) => setSourceText(e.target.value)}
                     className="w-full h-48 p-4 bg-input border border-border rounded-xl focus:ring-2 focus:ring-brand/20 focus:border-brand outline-none resize-none text-sm leading-relaxed text-txt placeholder:text-muted"
                     placeholder="Paste chapter content, summary, or notes here..."
                   />
                ) : (
                   <div className="border-2 border-dashed border-border rounded-xl p-10 text-center bg-page hover:bg-muted/5 transition-colors group">
                      <input type="file" id="quiz-file" className="hidden" accept=".pdf,.txt,.docx" onChange={(e) => {
                          if (e.target.files?.[0]) {
                              setSourceFile(e.target.files[0]); 
                              setSourceText("");
                          }
                      }} />
                      <label htmlFor="quiz-file" className="cursor-pointer flex flex-col items-center">
                        <div className="p-4 bg-brand/5 rounded-full mb-4 group-hover:scale-110 transition-transform">
                            <Upload className="w-8 h-8 text-brand" />
                        </div>
                        <span className="text-base font-bold text-brand">Click to upload document</span>
                        <span className="text-xs text-muted mt-2">PDF, DOCX, TXT supported</span>
                        {sourceFile && (
                          <div className="mt-4 flex items-center gap-2 bg-green-50 text-green-700 border border-green-200 px-4 py-1.5 rounded-full text-sm font-bold shadow-sm">
                             <FileText className="w-4 h-4" /> {sourceFile.name}
                          </div>
                        )}
                      </label>
                   </div>
                )}

                {error && (
                   <div className="mt-4 p-3 bg-red-500/10 border border-red-500/20 text-red-600 text-sm rounded-lg flex items-center gap-2">
                      <AlertCircle className="w-4 h-4" /> {error}
                   </div>
                )}

                <button 
                  onClick={handleStartGame}
                  className="w-full mt-6 py-4 bg-brand text-inv rounded-xl font-bold text-lg shadow-lg shadow-brand/20 hover:bg-brand-hover hover:scale-[1.01] active:scale-[0.98] transition-all flex items-center justify-center gap-2"
                >
                   <Play className="w-5 h-5 fill-current" /> Start Quiz
                </button>
             </div>
         </div>

      </div>
    </div>
  );
};

export default QuizGame;
