import React, { useState, useRef } from 'react';
import { GoogleGenAI } from "@google/genai";
import { 
  BrainCircuit, 
  Upload, 
  FileText, 
  Sparkles, 
  RefreshCw, 
  CheckCircle, 
  AlertCircle, 
  Loader2, 
  Copy, 
  Download,
  ChevronDown,
  ChevronUp
} from 'lucide-react';
import { jsPDF } from 'jspdf';

const SYSTEM_INSTRUCTION = `You are an advanced educational AI engine named "Quizlein".

Your task is to generate a complete quiz or question paper strictly based on the provided input source content.

IMPORTANT RULES:
1. Use ONLY the provided input content. Do not add outside knowledge.
2. Do NOT repeat questions across retries if previous questions are provided.
3. Questions must fully cover the concepts in the input content.
4. The output must be structured, evaluation-ready, and suitable for database storage.

YOUR TASK:
1. Analyze the source content thoroughly.
2. Identify key concepts, definitions, formulas, and explanations.
3. Generate a quiz that:
   - Matches the requested question types
   - Assigns appropriate marks to each question
   - Includes correct answers
   - Includes brief explanations for answers
4. Ensure question variety and conceptual coverage.
5. If retry mode is enabled:
   - Generate new or rephrased questions
   - Avoid repeating earlier questions
   - Maintain the same difficulty and syllabus coverage

OUTPUT FORMAT (STRICT JSON ONLY):

{
  "quiz_title": "<auto-generated based on content>",
  "source_summary": "<2–3 line summary of source>",
  "total_questions": <number>,
  "total_marks": <number>,
  "questions": [
    {
      "question_no": 1,
      "question_type": "MCQ | Short Answer | Long Answer",
      "question_text": "",
      "options": ["A", "B", "C", "D"],  // only for MCQ, otherwise null or empty
      "correct_answer": "",
      "explanation": "",
      "marks": 0,
      "difficulty": "easy | medium | hard"
    }
  ]
}

DO NOT:
- Add markdown (like \`\`\`json)
- Add commentary
- Add explanations outside JSON
- Change the JSON structure
`;

interface QuizQuestion {
  question_no: number;
  question_type: string;
  question_text: string;
  options?: string[];
  correct_answer: string;
  explanation: string;
  marks: number;
  difficulty: string;
}

interface QuizResult {
  quiz_title: string;
  source_summary: string;
  total_questions: number;
  total_marks: number;
  questions: QuizQuestion[];
}

const Quizlein = () => {
  // --- State ---
  const [activeTab, setActiveTab] = useState<'text' | 'file'>('text');
  const [sourceText, setSourceText] = useState("");
  const [sourceFile, setSourceFile] = useState<File | null>(null);
  
  // Config
  const [config, setConfig] = useState({
    type: 'Mixed', // MCQ, Short Answer, Long Answer, Mixed
    difficulty: 'Medium', // Easy, Medium, Hard
    count: 10,
    marks: 20
  });

  // App State
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<QuizResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  // Retry Context
  const [previousQuestions, setPreviousQuestions] = useState<string[]>([]);
  const [retryMode, setRetryMode] = useState(false);

  // --- Handlers ---

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setSourceFile(e.target.files[0]);
      setSourceText(""); // Clear text if file is chosen
      setResult(null); // Reset result on new source
      setPreviousQuestions([]); // Reset history
    }
  };

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const res = reader.result as string;
        const base64 = res.split(',')[1];
        resolve(base64);
      };
      reader.onerror = error => reject(error);
    });
  };

  const generateQuiz = async (isRetry: boolean = false) => {
    if ((activeTab === 'text' && !sourceText.trim()) || (activeTab === 'file' && !sourceFile)) {
      setError("Please provide source content.");
      return;
    }

    setLoading(true);
    setError(null);
    setRetryMode(isRetry);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      
      const userPrompt = `
        INPUT PARAMETERS:
        - Quiz Type: ${config.type}
        - Difficulty Distribution: ${config.difficulty}
        - Total Questions: ${config.count}
        - Total Marks: ${config.marks}
        - Retry Mode: ${isRetry}
        ${isRetry ? `- Previous Questions to Avoid: ${JSON.stringify(previousQuestions)}` : ''}

        SOURCE CONTENT:
        ${activeTab === 'text' ? sourceText : '(See attached file)'}
      `;

      const parts: any[] = [];
      
      if (activeTab === 'file' && sourceFile) {
        const base64 = await fileToBase64(sourceFile);
        parts.push({
          inlineData: {
            mimeType: sourceFile.type,
            data: base64
          }
        });
      }
      
      parts.push({ text: userPrompt });

      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: { parts },
        config: {
          systemInstruction: SYSTEM_INSTRUCTION,
          responseMimeType: 'application/json',
          temperature: 0.4
        }
      });

      const text = response.text;
      if (!text) throw new Error("No content generated");

      const parsed: QuizResult = JSON.parse(text);
      setResult(parsed);
      
      // Update history for next retry
      const newQuestionTexts = parsed.questions.map(q => q.question_text);
      setPreviousQuestions(prev => [...prev, ...newQuestionTexts]);

    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to generate quiz.");
    } finally {
      setLoading(false);
    }
  };

  const downloadJSON = () => {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Quiz_${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };
  
  const downloadPDF = () => {
    if (!result) return;
    const doc = new jsPDF();
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(result.quiz_title || "Generated Quiz", 15, 20);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const summary = doc.splitTextToSize(result.source_summary || "", 180);
    doc.text(summary, 15, 30);
    
    doc.line(15, 40, 195, 40);
    
    let y = 50;
    
    result.questions.forEach((q) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      const qText = doc.splitTextToSize(`Q${q.question_no}. ${q.question_text} (${q.marks} Marks)`, 180);
      doc.text(qText, 15, y);
      y += (qText.length * 5) + 2;
      
      if (q.options && q.options.length > 0) {
        doc.setFont("helvetica", "normal");
        q.options.forEach((opt, i) => {
           const label = String.fromCharCode(65 + i); // A, B, C...
           doc.text(`(${label}) ${opt}`, 20, y);
           y += 6;
        });
      }
      y += 4;
    });

    // Answer Key Page
    doc.addPage();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Answer Key & Explanations", 15, 20);
    
    y = 35;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    
    result.questions.forEach((q) => {
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
        const text = doc.splitTextToSize(`${q.question_no}. ${q.correct_answer} - ${q.explanation}`, 180);
        doc.text(text, 15, y);
        y += (text.length * 5) + 4;
    });

    doc.save("Quizlein_Export.pdf");
  };

  return (
    <div className="min-h-screen bg-page pb-12 font-sans">
      
      {/* Header */}
      <div className="bg-card border-b border-border sticky top-0 z-20">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-3">
             <div className="p-2 bg-indigo-100 text-indigo-700 rounded-lg">
               <BrainCircuit className="w-5 h-5" />
             </div>
             <div>
               <h1 className="text-xl font-bold text-txt">Quizlein AI</h1>
               <p className="text-xs text-muted font-medium">Intelligent Quiz Generator</p>
             </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* LEFT: Input & Config */}
        <div className="lg:col-span-4 space-y-6">
           
           {/* Source Input */}
           <div className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
              <div className="flex border-b border-border">
                  <button 
                    onClick={() => setActiveTab('text')}
                    className={`flex-1 py-3 text-sm font-semibold transition-colors ${activeTab === 'text' ? 'bg-card text-indigo-600 border-b-2 border-indigo-600' : 'bg-muted/5 text-muted hover:text-txt'}`}
                  >
                    Paste Text
                  </button>
                  <button 
                    onClick={() => setActiveTab('file')}
                    className={`flex-1 py-3 text-sm font-semibold transition-colors ${activeTab === 'file' ? 'bg-card text-indigo-600 border-b-2 border-indigo-600' : 'bg-muted/5 text-muted hover:text-txt'}`}
                  >
                    Upload File
                  </button>
              </div>
              
              <div className="p-5">
                 {activeTab === 'text' ? (
                   <textarea 
                     value={sourceText}
                     onChange={(e) => setSourceText(e.target.value)}
                     className="w-full h-48 p-3 text-sm bg-input border border-border rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none resize-none"
                     placeholder="Paste notes, article, or chapter content here..."
                   />
                 ) : (
                    <div className="border-2 border-dashed border-border rounded-lg p-8 text-center bg-page hover:bg-muted/10 transition-colors">
                      <input type="file" id="quiz-file" className="hidden" accept=".pdf,.txt,.docx" onChange={handleFileChange} />
                      <label htmlFor="quiz-file" className="cursor-pointer flex flex-col items-center">
                        <Upload className="w-8 h-8 text-muted mb-2" />
                        <span className="text-sm font-medium text-indigo-600">Choose File</span>
                        <span className="text-xs text-muted mt-1">PDF, DOCX, TXT supported</span>
                        {sourceFile && (
                          <div className="mt-3 flex items-center gap-2 bg-indigo-50 text-indigo-700 px-3 py-1.5 rounded-full text-xs font-bold">
                             <FileText className="w-3 h-3" /> {sourceFile.name}
                          </div>
                        )}
                      </label>
                   </div>
                 )}
              </div>
           </div>

           {/* Configuration */}
           <div className="bg-card rounded-xl border border-border shadow-sm p-5 space-y-4">
               <h3 className="text-sm font-bold text-txt uppercase tracking-wider text-muted">Quiz Settings</h3>
               
               <div className="grid grid-cols-2 gap-4">
                  <div>
                     <label className="text-xs font-medium text-txt mb-1.5 block">Question Type</label>
                     <select 
                       value={config.type}
                       onChange={e => setConfig({...config, type: e.target.value})}
                       className="w-full text-sm bg-input border border-border rounded-lg px-3 py-2 outline-none focus:border-indigo-500"
                     >
                        <option value="MCQ">MCQ Only</option>
                        <option value="Short Answer">Short Answer</option>
                        <option value="Long Answer">Long Answer</option>
                        <option value="Mixed">Mixed</option>
                     </select>
                  </div>
                  <div>
                     <label className="text-xs font-medium text-txt mb-1.5 block">Difficulty</label>
                     <select 
                       value={config.difficulty}
                       onChange={e => setConfig({...config, difficulty: e.target.value})}
                       className="w-full text-sm bg-input border border-border rounded-lg px-3 py-2 outline-none focus:border-indigo-500"
                     >
                        <option value="Easy">Easy</option>
                        <option value="Medium">Medium</option>
                        <option value="Hard">Hard</option>
                     </select>
                  </div>
               </div>
               
               <div className="grid grid-cols-2 gap-4">
                  <div>
                     <label className="text-xs font-medium text-txt mb-1.5 block">Question Count</label>
                     <input 
                       type="number" 
                       min="1" max="50"
                       value={config.count}
                       onChange={e => setConfig({...config, count: parseInt(e.target.value)})}
                       className="w-full text-sm bg-input border border-border rounded-lg px-3 py-2 outline-none focus:border-indigo-500"
                     />
                  </div>
                  <div>
                     <label className="text-xs font-medium text-txt mb-1.5 block">Total Marks</label>
                     <input 
                       type="number" 
                       min="5" max="100"
                       value={config.marks}
                       onChange={e => setConfig({...config, marks: parseInt(e.target.value)})}
                       className="w-full text-sm bg-input border border-border rounded-lg px-3 py-2 outline-none focus:border-indigo-500"
                     />
                  </div>
               </div>

               <button 
                 onClick={() => generateQuiz(false)}
                 disabled={loading}
                 className="w-full mt-2 py-3 bg-indigo-600 text-white font-bold rounded-lg shadow-lg shadow-indigo-200 hover:bg-indigo-700 active:scale-[0.98] transition-all flex items-center justify-center gap-2 disabled:opacity-70 disabled:pointer-events-none"
               >
                 {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
                 {loading ? 'Analyzing Content...' : 'Generate Quiz'}
               </button>
           </div>
           
           {error && (
             <div className="p-4 bg-red-50 text-red-600 text-sm rounded-xl flex items-start gap-3 border border-red-100 animate-in fade-in">
                <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
                <p>{error}</p>
             </div>
           )}

        </div>

        {/* RIGHT: Output */}
        <div className="lg:col-span-8 flex flex-col h-full min-h-[500px]">
           {result ? (
              <div className="flex-1 flex flex-col gap-6 animate-in slide-in-from-bottom-4 duration-500">
                  {/* Summary Card */}
                  <div className="bg-card rounded-xl border border-border shadow-sm p-6 relative overflow-hidden">
                      <div className="absolute top-0 right-0 p-4 opacity-10">
                          <BrainCircuit className="w-24 h-24 text-indigo-600" />
                      </div>
                      <div className="relative z-10">
                          <h2 className="text-2xl font-bold text-txt mb-2">{result.quiz_title}</h2>
                          <p className="text-muted text-sm leading-relaxed mb-4 max-w-2xl">{result.source_summary}</p>
                          <div className="flex gap-4">
                              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-bold border border-blue-100">
                                <CheckCircle className="w-3 h-3" /> {result.total_questions} Questions
                              </span>
                              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-purple-50 text-purple-700 text-xs font-bold border border-purple-100">
                                <Sparkles className="w-3 h-3" /> {result.total_marks} Marks
                              </span>
                          </div>
                      </div>
                  </div>

                  {/* Actions Bar */}
                  <div className="flex flex-wrap items-center justify-between gap-3">
                      <div className="flex gap-2">
                          <button onClick={downloadJSON} className="flex items-center gap-2 px-4 py-2 bg-card border border-border rounded-lg text-sm font-medium hover:bg-muted/10 transition-colors">
                             <Copy className="w-4 h-4" /> JSON
                          </button>
                          <button onClick={downloadPDF} className="flex items-center gap-2 px-4 py-2 bg-card border border-border rounded-lg text-sm font-medium hover:bg-muted/10 transition-colors">
                             <Download className="w-4 h-4" /> PDF
                          </button>
                      </div>
                      <button 
                        onClick={() => generateQuiz(true)} 
                        disabled={loading}
                        className="flex items-center gap-2 px-4 py-2 bg-white text-indigo-600 border border-indigo-200 rounded-lg text-sm font-bold hover:bg-indigo-50 transition-colors shadow-sm disabled:opacity-50"
                      >
                         <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} /> Regenerate (Retry)
                      </button>
                  </div>

                  {/* Questions List */}
                  <div className="space-y-4">
                      {result.questions.map((q, idx) => (
                          <QuestionCard key={idx} data={q} />
                      ))}
                  </div>

              </div>
           ) : (
              <div className="flex-1 bg-card rounded-xl border border-border border-dashed flex flex-col items-center justify-center text-center p-8 opacity-60">
                 <div className="w-20 h-20 bg-muted/10 rounded-full flex items-center justify-center mb-6">
                    <BrainCircuit className="w-10 h-10 text-muted" />
                 </div>
                 <h3 className="text-xl font-bold text-txt mb-2">Ready to Generate</h3>
                 <p className="text-muted max-w-sm">
                    Enter your source content on the left, configure your preferences, and let Quizlein create a structured quiz for you.
                 </p>
              </div>
           )}
        </div>

      </div>
    </div>
  );
};

const QuestionCard: React.FC<{ data: QuizQuestion }> = ({ data }) => {
  const [showAnswer, setShowAnswer] = useState(false);

  return (
    <div className="bg-card rounded-xl border border-border shadow-sm p-5 hover:border-indigo-200 transition-colors">
       <div className="flex justify-between items-start mb-3">
          <div className="flex items-center gap-2">
             <span className="bg-indigo-600 text-white w-6 h-6 rounded-md flex items-center justify-center text-xs font-bold">
               {data.question_no}
             </span>
             <span className="text-xs font-bold text-indigo-600 uppercase tracking-wide bg-indigo-50 px-2 py-0.5 rounded">
               {data.question_type}
             </span>
          </div>
          <span className="text-xs font-bold text-muted">{data.marks} Marks</span>
       </div>
       
       <h4 className="text-txt font-medium mb-4">{data.question_text}</h4>
       
       {data.options && data.options.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
             {data.options.map((opt, i) => (
                <div key={i} className="flex items-center gap-3 p-3 rounded-lg border border-border bg-page/50 text-sm">
                   <span className="w-5 h-5 rounded-full border border-gray-300 flex items-center justify-center text-[10px] text-gray-500 font-bold">
                      {String.fromCharCode(65 + i)}
                   </span>
                   <span className="text-txt">{opt}</span>
                </div>
             ))}
          </div>
       )}

       <button 
         onClick={() => setShowAnswer(!showAnswer)}
         className="flex items-center gap-2 text-xs font-bold text-muted hover:text-indigo-600 transition-colors"
       >
          {showAnswer ? <ChevronUp className="w-3 h-3"/> : <ChevronDown className="w-3 h-3"/>}
          {showAnswer ? 'Hide Answer' : 'Show Answer'}
       </button>

       {showAnswer && (
          <div className="mt-3 p-4 bg-green-50 rounded-lg border border-green-100 animate-in slide-in-from-top-2">
             <div className="flex gap-2 mb-1">
                <span className="text-xs font-bold text-green-700 uppercase">Correct Answer:</span>
                <span className="text-sm font-semibold text-gray-900">{data.correct_answer}</span>
             </div>
             <p className="text-xs text-green-800 leading-relaxed">
                <span className="font-bold">Explanation:</span> {data.explanation}
             </p>
          </div>
       )}
    </div>
  );
};

export default Quizlein;