import React from 'react';
import { FileText, Scale, CheckCircle, AlertTriangle } from 'lucide-react';

const Terms = () => {
  return (
    <div className="p-6 max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="text-center mb-12">
        <div className="w-16 h-16 bg-brand/10 text-brand rounded-2xl flex items-center justify-center mx-auto mb-4">
          <Scale className="w-8 h-8" />
        </div>
        <h1 className="text-3xl font-bold text-txt">Terms of Service</h1>
        <p className="text-muted mt-2">Last updated: April 23, 2026</p>
      </div>

      <div className="space-y-8">
        {/* Acceptance */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border">
          <h2 className="text-xl font-bold text-txt mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5 text-brand" />
            Acceptance of Terms
          </h2>
          <p className="text-muted leading-relaxed">
            By accessing or using QPGPT's AI-powered learning platform, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
          </p>
        </div>

        {/* Services */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border">
          <h2 className="text-xl font-bold text-txt mb-4">Our Services</h2>
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <p className="text-muted">AI-powered question paper generation from your study materials</p>
            </div>
            <div className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <p className="text-muted">Access to a global library of past papers and educational content</p>
            </div>
            <div className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <p className="text-muted">Interactive quiz games for gamified learning</p>
            </div>
            <div className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <p className="text-muted">QPGPT AI chat for study assistance and doubt resolution</p>
            </div>
          </div>
        </div>

        {/* User Responsibilities */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border">
          <h2 className="text-xl font-bold text-txt mb-4">User Responsibilities</h2>
          <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-4 mb-4 flex items-center gap-3">
            <AlertTriangle className="w-5 h-5 text-yellow-600 flex-shrink-0" />
            <span className="text-yellow-800 text-sm">You agree NOT to use our platform for any illegal or harmful purposes.</span>
          </div>
          <ul className="space-y-3">
            <li className="flex items-center gap-3 text-muted">
              <div className="w-2 h-2 bg-brand rounded-full"></div>
              Keep your account credentials secure and confidential
            </li>
            <li className="flex items-center gap-3 text-muted">
              <div className="w-2 h-2 bg-brand rounded-full"></div>
              Not upload copyrighted material without proper authorization
            </li>
            <li className="flex items-center gap-3 text-muted">
              <div className="w-2 h-2 bg-brand rounded-full"></div>
              Not attempt to circumvent or exploit system security measures
            </li>
            <li className="flex items-center gap-3 text-muted">
              <div className="w-2 h-2 bg-brand rounded-full"></div>
              Use generated content responsibly and in accordance with academic integrity
            </li>
          </ul>
        </div>

        {/* Intellectual Property */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border">
          <h2 className="text-xl font-bold text-txt mb-4">Intellectual Property</h2>
          <div className="space-y-4">
            <div className="bg-input p-4 rounded-xl">
              <h3 className="font-semibold text-txt text-sm mb-1">Your Content</h3>
              <p className="text-muted text-sm">You retain ownership of content you upload. By uploading, you grant us a license to process and store it for service delivery.</p>
            </div>
            <div className="bg-input p-4 rounded-xl">
              <h3 className="font-semibold text-txt text-sm mb-1">Generated Content</h3>
              <p className="text-muted text-sm">Content generated by our AI is for your personal educational use. Redistribution for commercial purposes is prohibited.</p>
            </div>
            <div className="bg-input p-4 rounded-xl">
              <h3 className="font-semibold text-txt text-sm mb-1">Platform</h3>
              <p className="text-muted text-sm">QPGPT branding, logos, and design elements are our property and may not be reproduced without permission.</p>
            </div>
          </div>
        </div>

        {/* Limitation of Liability */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border">
          <h2 className="text-xl font-bold text-txt mb-4">Limitation of Liability</h2>
          <p className="text-muted leading-relaxed">
            QPGPT provides educational tools "as is". While we strive for accuracy in AI-generated content, we cannot guarantee 100% correctness. We are not liable for any damages arising from the use of our platform.
          </p>
        </div>

        {/* Account Termination */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border">
          <h2 className="text-xl font-bold text-txt mb-4">Account Termination</h2>
          <p className="text-muted leading-relaxed mb-4">
            We reserve the right to suspend or terminate accounts that violate these terms or engage in harmful activities. Users may also delete their account at any time through settings.
          </p>
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-center gap-3">
            <AlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0" />
            <span className="text-red-800 text-sm font-medium">Violations may result in immediate account suspension without notice.</span>
          </div>
        </div>

        {/* Changes to Terms */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border">
          <h2 className="text-xl font-bold text-txt mb-4">Changes to Terms</h2>
          <p className="text-muted leading-relaxed">
            We may update these terms periodically. Significant changes will be communicated via email or platform notifications. Continued use after changes constitutes acceptance of new terms.
          </p>
        </div>

        {/* Contact */}
        <div className="bg-card p-8 rounded-2xl shadow-glass border border-border text-center">
          <h2 className="text-xl font-bold text-txt mb-2">Questions?</h2>
          <p className="text-muted mb-4">If you have any questions about these Terms of Service, please contact us.</p>
          <a href="#/contact" className="inline-flex items-center gap-2 text-brand font-semibold hover:underline">
            Contact Our Legal Team
          </a>
        </div>
      </div>
    </div>
  );
};

export default Terms;